import type { Shipment, AIAgent, DashboardStats, User } from "./types"

export const mockUser: User = {
  id: "user-1",
  email: "demo@trademind.ai",
  name: "Demo User",
  role: "exporter",
  company: "Global Trade Corp",
  createdAt: new Date("2024-01-01"),
}

export const mockAgents: AIAgent[] = [
  {
    id: "agent-1",
    name: "Document Intake Agent",
    type: "document_intake",
    status: "idle",
    progress: 100,
    lastRun: new Date(Date.now() - 1000 * 60 * 5),
    metrics: {
      totalProcessed: 1247,
      successRate: 98.5,
      avgProcessingTime: 2.3,
    },
  },
  {
    id: "agent-2",
    name: "Validation Agent",
    type: "validation",
    status: "idle",
    progress: 100,
    lastRun: new Date(Date.now() - 1000 * 60 * 3),
    metrics: {
      totalProcessed: 1198,
      successRate: 96.2,
      avgProcessingTime: 3.1,
    },
  },
  {
    id: "agent-3",
    name: "HS Code Classifier",
    type: "hs_code",
    status: "idle",
    progress: 100,
    lastRun: new Date(Date.now() - 1000 * 60 * 2),
    metrics: {
      totalProcessed: 1156,
      successRate: 94.8,
      avgProcessingTime: 4.7,
    },
  },
  {
    id: "agent-4",
    name: "Duty Calculator",
    type: "duty",
    status: "idle",
    progress: 100,
    lastRun: new Date(Date.now() - 1000 * 60 * 4),
    metrics: {
      totalProcessed: 1142,
      successRate: 99.1,
      avgProcessingTime: 1.8,
    },
  },
  {
    id: "agent-5",
    name: "Compliance Checker",
    type: "compliance",
    status: "idle",
    progress: 100,
    lastRun: new Date(Date.now() - 1000 * 60 * 6),
    metrics: {
      totalProcessed: 1138,
      successRate: 97.3,
      avgProcessingTime: 5.2,
    },
  },
  {
    id: "agent-6",
    name: "Risk Scoring Agent",
    type: "risk",
    status: "idle",
    progress: 100,
    lastRun: new Date(Date.now() - 1000 * 60 * 1),
    metrics: {
      totalProcessed: 1134,
      successRate: 98.9,
      avgProcessingTime: 2.9,
    },
  },
]

export const mockShipments: Shipment[] = [
  {
    id: "ship-1",
    userId: "user-1",
    referenceNumber: "TM-2025-001",
    status: "cleared",
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-16"),
    exporter: {
      name: "Global Trade Corp",
      address: "123 Export St, New York, NY",
      country: "USA",
    },
    importer: {
      name: "European Imports Ltd",
      address: "456 Import Ave, London",
      country: "UK",
    },
    goods: {
      description: "Electronic Components - Semiconductors",
      quantity: 5000,
      unit: "pieces",
      value: 125000,
      currency: "USD",
      weight: 250,
      weightUnit: "kg",
    },
    documents: [
      {
        id: "doc-1",
        shipmentId: "ship-1",
        type: "commercial_invoice",
        fileName: "invoice_001.pdf",
        fileUrl: "/commercial-invoice.jpg",
        uploadedAt: new Date("2025-01-15"),
        validationStatus: "valid",
      },
      {
        id: "doc-2",
        shipmentId: "ship-1",
        type: "packing_list",
        fileName: "packing_list_001.pdf",
        fileUrl: "/packing-list.jpg",
        uploadedAt: new Date("2025-01-15"),
        validationStatus: "valid",
      },
    ],
    hsCode: {
      code: "8542.31",
      description: "Electronic integrated circuits: Processors and controllers",
      confidence: 96.5,
      category: "Electronics",
    },
    dutyCalculation: {
      hsCode: "8542.31",
      baseValue: 125000,
      dutyRate: 0,
      dutyAmount: 0,
      taxAmount: 25000,
      totalAmount: 25000,
      currency: "USD",
    },
    complianceChecks: [
      {
        id: "comp-1",
        rule: "Export License Verification",
        status: "passed",
        message: "Valid export license found",
        severity: "high",
      },
      {
        id: "comp-2",
        rule: "Dual-Use Goods Check",
        status: "passed",
        message: "No dual-use restrictions apply",
        severity: "medium",
      },
    ],
    riskScore: {
      overall: 15,
      factors: {
        documentCompleteness: 95,
        complianceHistory: 98,
        valueAccuracy: 92,
        originVerification: 94,
      },
      level: "low",
      recommendations: ["Shipment cleared for processing"],
    },
    agentResults: {},
    blockchainRecords: [
      {
        id: "block-1",
        shipmentId: "ship-1",
        action: "Shipment Created",
        timestamp: new Date("2025-01-15T10:00:00"),
        hash: "0x1a2b3c4d5e6f",
        previousHash: "0x0000000000",
        data: { status: "draft" },
      },
      {
        id: "block-2",
        shipmentId: "ship-1",
        action: "Documents Validated",
        timestamp: new Date("2025-01-15T10:15:00"),
        hash: "0x2b3c4d5e6f7g",
        previousHash: "0x1a2b3c4d5e6f",
        data: { documentsValid: true },
      },
    ],
    optimizedRoute: {
      path: ["New York Port", "Atlantic Ocean", "London Port"],
      estimatedCost: 8500,
      estimatedTime: 14,
      confidence: 94.2,
    },
  },
  {
    id: "ship-2",
    userId: "user-1",
    referenceNumber: "TM-2025-002",
    status: "processing",
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-20"),
    exporter: {
      name: "Global Trade Corp",
      address: "123 Export St, New York, NY",
      country: "USA",
    },
    importer: {
      name: "Asian Electronics Co",
      address: "789 Tech Blvd, Singapore",
      country: "Singapore",
    },
    goods: {
      description: "Medical Equipment - Diagnostic Devices",
      quantity: 50,
      unit: "units",
      value: 450000,
      currency: "USD",
      weight: 1200,
      weightUnit: "kg",
    },
    documents: [
      {
        id: "doc-3",
        shipmentId: "ship-2",
        type: "commercial_invoice",
        fileName: "invoice_002.pdf",
        fileUrl: "/medical-invoice.jpg",
        uploadedAt: new Date("2025-01-20"),
        validationStatus: "pending",
      },
    ],
    complianceChecks: [],
    agentResults: {},
    blockchainRecords: [
      {
        id: "block-3",
        shipmentId: "ship-2",
        action: "Shipment Created",
        timestamp: new Date("2025-01-20T14:30:00"),
        hash: "0x3c4d5e6f7g8h",
        previousHash: "0x2b3c4d5e6f7g",
        data: { status: "draft" },
      },
    ],
  },
]

export const mockDashboardStats: DashboardStats = {
  totalShipments: 1247,
  activeShipments: 23,
  clearedShipments: 1198,
  avgProcessingTime: 3.2,
  totalDutiesPaid: 12450000,
  complianceRate: 97.8,
  riskDistribution: {
    low: 1089,
    medium: 98,
    high: 52,
    critical: 8,
  },
}
